version: '3.5'

networks:
    app-network:
        name: ${APP_NAME}-network

services:

    app:
        container_name: ${APP_NAME}-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "9000:9000"
        env_file: 
            - ./docker/docker.env
        networks:
            - app-network
 
    database:
        container_name: ${APP_NAME}-mysql
        image: mysql:5.7.29   
        restart: unless-stopped
        tty: true
        user: 1000:1000
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        env_file:
            - ./docker/docker.env
        networks:
            - app-network
    
    redis:
        container_name: ${APP_NAME}-redis
        image: "redis:alpine"
        restart: unless-stopped
        user: 1000:1000
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis:/data
        networks:
            - app-network

    composer:
        container_name: ${APP_NAME}-composer
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        user: 1000:1000
        depends_on:
            - app
        entrypoint: ['composer', '--ignore-platform-reqs']
        command: "install"
        networks: 
            - app-network
    
    artisan:
        container_name: ${APP_NAME}-artisan
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/app
        depends_on: 
            - database
            - composer
        entrypoint: ['/app/artisan']
        networks: 
            - app-network    
    
    webserver: 
        container_name: ${APP_NAME}-nginx
        image: nginx:stable-alpine
        ports:
            - "8088:80"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - database
            - redis
        networks:
            - app-network









